/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check and system introspection
         * @description Returns service status, ripgrep availability, app version, OS info, environment variables, and hook configuration.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compress file to seekable zstd format (background task)
         * @description Creates a background task that encodes the file to .zst. Poll /v1/tasks/{id} for progress. The input path and the effective output path are both validated against --search-root.
         */
        post: operations["compress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/detectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all available anomaly detectors
         * @description Returns metadata about every registered detector, plus the severity-scale legend.
         */
        get: operations["list-detectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cached index data for a file
         * @description Returns the cached UnifiedFileIndex, or 404 if no index exists yet.
         */
        get: operations["index-get"];
        put?: never;
        /**
         * Build line index for file (background task)
         * @description Creates a background task that indexes the file. Poll /v1/tasks/{id} for progress.
         */
        post: operations["index-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get context lines around byte offsets or line numbers
         * @description Use this endpoint to view actual content around matches from /v1/trace.
         */
        get: operations["samples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get status of a background task
         * @description Returns queued/running/completed/failed state and, on completion, the task result.
         */
        get: operations["task-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search file for regex patterns (supports multiple patterns)
         * @description Uses ripgrep to scan one or more paths for one or more regex patterns, returning match offsets.
         */
        get: operations["trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List directory contents
         * @description Lists files and directories within --search-root, with size/type/index metadata.
         */
        get: operations["tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ApiError.json
             */
            readonly $schema?: string;
            detail: string;
        };
        CategoryInfo: {
            /** @description One sentence describing what this category covers. */
            description: string;
            /** @description Names of the detectors that report under this category. */
            detectors: string[] | null;
            /** @description Stable category identifier, kebab-case. Used as the category field of an anomaly. */
            name: string;
        };
        CompressRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CompressRequest.json
             */
            readonly $schema?: string;
            build_index: boolean;
            /** Format: int64 */
            compression_level: number;
            force: boolean;
            frame_size: string;
            /** @description Path to the input file. Must be inside a configured --search-root. */
            input_path: string;
            /** @description Path for the output .zst file (default: input_path + ".zst"). Must be inside a configured --search-root. */
            output_path: string | null;
        };
        ContextLine: {
            /** Format: int64 */
            absolute_line_number: number;
            /** Format: int64 */
            absolute_offset: number;
            line_text: string;
            /** Format: int64 */
            relative_line_number: number;
        };
        DetectorInfo: {
            /** @description The category this detector reports anomalies under. Categories are backend-defined; read them from this response rather than hardcoding a list. */
            category: string;
            /** @description One sentence describing what the detector looks for, suitable for a tooltip. */
            description: string;
            /** @description Short lines that would trigger this detector. May be empty. */
            examples: string[] | null;
            /** @description Stable identifier, kebab-case (e.g. "traceback-python"). Never display-formatted; use it as a key. */
            name: string;
            /** @description The severity band this detector can emit. Use it to scale a UI indicator without waiting for real anomalies. */
            severity_range: components["schemas"]["SeverityRange"];
        };
        DetectorsResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DetectorsResponse.json
             */
            readonly $schema?: string;
            /** @description The categories the registered detectors report under. */
            categories: components["schemas"]["CategoryInfo"][] | null;
            /** @description Every detector this backend has registered. The two backends ship different sets, so a client must render whatever it is given. */
            detectors: components["schemas"]["DetectorInfo"][] | null;
            /** @description The severity bands, always populated regardless of how many detectors are registered. */
            severity_scale: components["schemas"]["SeverityScaleLevel"][] | null;
        };
        HealthResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthResponse.json
             */
            readonly $schema?: string;
            app_version: string;
            constants: {
                [key: string]: unknown;
            };
            /** @description HTTP wire contract version, MAJOR.MINOR */
            contract_version: string;
            docs_url: string;
            environment: {
                [key: string]: string;
            };
            go_packages: {
                [key: string]: string;
            };
            go_version: string;
            hooks: {
                [key: string]: unknown;
            };
            os_info: {
                [key: string]: string;
            };
            ripgrep_available: boolean;
            search_roots: string[] | null;
            status: string;
            system_resources: {
                [key: string]: unknown;
            };
        };
        IndexRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/IndexRequest.json
             */
            readonly $schema?: string;
            analyze?: boolean;
            /** Format: int64 */
            analyze_window_lines?: number;
            force?: boolean;
            path: string;
            /** Format: int64 */
            threshold?: number;
        };
        Match: {
            /** Format: int64 */
            absolute_line_number: number;
            file: string;
            line_text: string | null;
            /** Format: int64 */
            offset: number;
            pattern: string;
            /** Format: int64 */
            relative_line_number: number | null;
            submatches: components["schemas"]["Submatch"][] | null;
        };
        SamplesResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SamplesResponse.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            after_context: number;
            /** Format: int64 */
            before_context: number;
            cli_command: string | null;
            compression_format: string | null;
            is_compressed: boolean;
            lines: {
                [key: string]: number;
            };
            offsets: {
                [key: string]: number;
            };
            path: string;
            samples: {
                [key: string]: string[] | null;
            };
        };
        SeverityRange: {
            /**
             * Format: double
             * @description Highest severity this detector emits, 0.0 to 1.0
             */
            max: number;
            /**
             * Format: double
             * @description Lowest severity this detector emits, 0.0 to 1.0
             */
            min: number;
        };
        SeverityScaleLevel: {
            /** @description One sentence on what this level means for a reader */
            description: string;
            /** @description Display name for the level (e.g. "high") */
            label: string;
            /**
             * Format: double
             * @description Inclusive upper bound of this level, 0.0 to 1.0
             */
            max: number;
            /**
             * Format: double
             * @description Inclusive lower bound of this level, 0.0 to 1.0
             */
            min: number;
        };
        Submatch: {
            /** Format: int64 */
            end: number;
            /** Format: int64 */
            start: number;
            text: string;
        };
        TaskResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TaskResponse.json
             */
            readonly $schema?: string;
            message: string;
            path: string;
            started_at: string | null;
            status: string;
            task_id: string;
        };
        TaskStatusResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TaskStatusResponse.json
             */
            readonly $schema?: string;
            completed_at: string | null;
            error: string | null;
            operation: string;
            path: string;
            result: {
                [key: string]: unknown;
            };
            started_at: string | null;
            status: string;
            task_id: string;
        };
        TraceResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TraceResponse.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            after_context: number | null;
            /** Format: int64 */
            before_context: number | null;
            cli_command: string | null;
            context_lines: {
                [key: string]: components["schemas"]["ContextLine"][] | null;
            };
            file_chunks: {
                [key: string]: number;
            };
            files: {
                [key: string]: string;
            };
            matches: components["schemas"]["Match"][];
            /** Format: int64 */
            max_results: number | null;
            path: string[];
            patterns: {
                [key: string]: string;
            };
            request_id: string;
            scanned_files: string[];
            skipped_files: string[];
            /** Format: double */
            time: number;
        };
        TreeEntry: {
            /** Format: int64 */
            children_count: number | null;
            compression_format: string | null;
            is_compressed: boolean | null;
            is_indexed: boolean | null;
            is_text: boolean | null;
            /** Format: int64 */
            line_count: number | null;
            modified_at: string | null;
            name: string;
            path: string;
            /** Format: int64 */
            size: number | null;
            size_human: string | null;
            type: string;
        };
        TreeResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TreeResponse.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["TreeEntry"][] | null;
            is_search_root: boolean;
            parent: string | null;
            path: string;
            /** Format: int64 */
            total_entries: number;
            /** Format: int64 */
            total_size: number | null;
            total_size_human: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    compress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "list-detectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectorsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "index-get": {
        parameters: {
            query: {
                /** @description File path to get index for */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "index-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    samples: {
        parameters: {
            query: {
                /** @description File path to read from */
                path: string;
                /** @description Comma-separated byte offsets or ranges */
                offsets?: string;
                /** @description Comma-separated 1-based line numbers or ranges */
                lines?: string;
                /** @description Context lines before AND after each offset (-1 = default 3) */
                context?: number;
                /** @description Context lines before each offset (-1 = default 3) */
                before_context?: number;
                /** @description Context lines after each offset (-1 = default 3) */
                after_context?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamplesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "task-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    trace: {
        parameters: {
            query: {
                /** @description File or directory path(s) to search */
                path: string[] | null;
                /** @description Regex pattern(s) to search for */
                regexp: string[] | null;
                /** @description Maximum results to return. 0 = unlimited. */
                max_results?: number;
                /** @description Custom UUID v7 request ID */
                request_id?: string;
                /** @description URL to POST when file scan completes */
                hook_on_file?: string;
                /** @description URL to POST per match. Requires max_results. */
                hook_on_match?: string;
                /** @description URL to POST when the whole trace completes */
                hook_on_complete?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    tree: {
        parameters: {
            query?: {
                /** @description Directory path to list. Omit to list search roots. */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
